---
version: 2
plan:
  project-key: RS
  key: COCL
  name: re-content-client
stages:
  - Build:
      - Create package

Create package:
  docker:
    image: php:7.4-cli
  tasks:
    - script: |
        apt-get update && apt-get install -y git unzip &&
        rm -rf code &&
        mkdir -p code &&
        (mv * .* code/ || true) &&

        cd code &&
        rm -rf .git &&
        tar czvf ../rs-re-content-client.tar.gz ./ &&
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&
        php composer-setup.php &&
        php -r "unlink('composer-setup.php');" &&
        php composer.phar install
  artifacts:
    - name: rs-re-content-client.tar.gz
      location: ./
      pattern: rs-re-content-client.tar.gz
      required: true
      shared: true
